
# .properties? ????? ?? ??
# yml, yaml? ?? ???? ???? ??

# port ?? ???, default? 8080
#server:
#  port: 8081

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/practice
    username: springboot
    password: 980315
  jpa:
    database: mysql
    # innoDB?? ??
    database-platform: org.hibernate.dialect.MariaDBDialect
    # ???? ?????, ???? ??? ??? ????
    generate-ddl: true
    # jpa? ???????, hibernate ???( ??? ?? ??)
    hibernate:
      # create??? ?? table? drop? ???
      # update???  ????? alter? ???? ??? ??? ??
      # ?????? ?? ?????? ????, ??? ????? ????? ??? ??.
      # validate? ?? DB ?? ??? check
      ddl-auto: update
      # ???? ddl, dml?? ???? ???? ??
    show-sql: true

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml